### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by tianyumyum** [Spico197/REx#22]
### What happened?

A bug happened!
ImportError: cannot import name 'ConfigParser' from 'rex.utils.config'

### Python Version

3.10

### PyTorch Version

2.0.1+cu118

### REx Version

0.0.7

### Relevant log output

```shell
bash /home/2023/myced/CatalogExtraction/examples/doc_tree_construction/train/run.sh
echo "$(git log -1)"
++ git log -1
fatal: 不是 git 仓库（或者直至挂载点 / 的任何父目录）
停止在文件系统边界（未设置 GIT_DISCOVERY_ACROSS_FILESYSTEM）。
+ echo ''

# git diff

# CONFIG_NAME=$1
# DEVICE=$2
DATA_TYPE=$1
+ DATA_TYPE=
DEVICE=$2
+ DEVICE=

shift 2
+ shift 2
ADDITIONAL_SETTINGS=$*
+ ADDITIONAL_SETTINGS=

export TOKENIZERS_PARALLELISM=true
+ export TOKENIZERS_PARALLELISM=true
+ TOKENIZERS_PARALLELISM=true

{
    for seed in 17 127 1227 12227 122227
    do
        python -u "/home/2023/myced/CatalogExtraction/examples/doc_tree_construction/train/run.py" \
            #-b "examples/doc_tree_construction/train/base_config.yaml" \
            -b "/home/2023/myced/CatalogExtraction/examples/doc_tree_construction/train/base_config.yaml" \
            #-c "examples/doc_tree_construction/train/custom.yaml" \
            -c "/home/2023/myced/CatalogExtraction/examples/doc_tree_construction/train/custom.yaml" \
            -a random_seed=$seed device="${DEVICE}" data_type="${DATA_TYPE}" ${ADDITIONAL_SETTINGS}
    done

    exit
}
+ for seed in 17 127 1227 12227 122227
+ python -u /home/2023/myced/CatalogExtraction/examples/doc_tree_construction/train/run.py
Traceback (most recent call last):
  File "/home/2023/myced/CatalogExtraction/examples/doc_tree_construction/train/run.py", line 3, in <module>
    from rex.utils.config import ConfigParser
ImportError: cannot import name 'ConfigParser' from 'rex.utils.config' (/home/2023/miniconda3/envs/doctree/lib/python3.10/site-packages/rex/utils/config.py)
+ -b /home/2023/myced/CatalogExtraction/examples/doc_tree_construction/train/base_config.yaml
/home/2023/myced/CatalogExtraction/examples/doc_tree_construction/train/run.sh: 行 23: -b: 未找到命令
+ -c /home/2023/myced/CatalogExtraction/examples/doc_tree_construction/train/custom.yaml -a random_seed=17 device= data_type=
/home/2023/myced/CatalogExtraction/examples/doc_tree_construction/train/run.sh: 行 25: -c: 未找到命令
+ for seed in 17 127 1227 12227 122227
+ python -u /home/2023/myced/CatalogExtraction/examples/doc_tree_construction/train/run.py
Traceback (most recent call last):
  File "/home/2023/myced/CatalogExtraction/examples/doc_tree_construction/train/run.py", line 3, in <module>
    from rex.utils.config import ConfigParser
ImportError: cannot import name 'ConfigParser' from 'rex.utils.config' (/home/2023/miniconda3/envs/doctree/lib/python3.10/site-packages/rex/utils/config.py)
+ -b /home/2023/myced/CatalogExtraction/examples/doc_tree_construction/train/base_config.yaml
/home/2023/myced/CatalogExtraction/examples/doc_tree_construction/train/run.sh: 行 23: -b: 未找到命令
+ -c /home/2023/myced/CatalogExtraction/examples/doc_tree_construction/train/custom.yaml -a random_seed=127 device= data_type=
/home/2023/myced/CatalogExtraction/examples/doc_tree_construction/train/run.sh: 行 25: -c: 未找到命令
+ for seed in 17 127 1227 12227 122227
+ python -u /home/2023/myced/CatalogExtraction/examples/doc_tree_construction/train/run.py
Traceback (most recent call last):
  File "/home/2023/myced/CatalogExtraction/examples/doc_tree_construction/train/run.py", line 3, in <module>
    from rex.utils.config import ConfigParser
ImportError: cannot import name 'ConfigParser' from 'rex.utils.config' (/home/2023/miniconda3/envs/doctree/lib/python3.10/site-packages/rex/utils/config.py)
+ -b /home/2023/myced/CatalogExtraction/examples/doc_tree_construction/train/base_config.yaml
/home/2023/myced/CatalogExtraction/examples/doc_tree_construction/train/run.sh: 行 23: -b: 未找到命令
+ -c /home/2023/myced/CatalogExtraction/examples/doc_tree_construction/train/custom.yaml -a random_seed=1227 device= data_type=
/home/2023/myced/CatalogExtraction/examples/doc_tree_construction/train/run.sh: 行 25: -c: 未找到命令
+ for seed in 17 127 1227 12227 122227
+ python -u /home/2023/myced/CatalogExtraction/examples/doc_tree_construction/train/run.py
Traceback (most recent call last):
  File "/home/2023/myced/CatalogExtraction/examples/doc_tree_construction/train/run.py", line 3, in <module>
    from rex.utils.config import ConfigParser
ImportError: cannot import name 'ConfigParser' from 'rex.utils.config' (/home/2023/miniconda3/envs/doctree/lib/python3.10/site-packages/rex/utils/config.py)
+ -b /home/2023/myced/CatalogExtraction/examples/doc_tree_construction/train/base_config.yaml
/home/2023/myced/CatalogExtraction/examples/doc_tree_construction/train/run.sh: 行 23: -b: 未找到命令
+ -c /home/2023/myced/CatalogExtraction/examples/doc_tree_construction/train/custom.yaml -a random_seed=12227 device= data_type=
/home/2023/myced/CatalogExtraction/examples/doc_tree_construction/train/run.sh: 行 25: -c: 未找到命令
+ for seed in 17 127 1227 12227 122227
+ python -u /home/2023/myced/CatalogExtraction/examples/doc_tree_construction/train/run.py
Traceback (most recent call last):
  File "/home/2023/myced/CatalogExtraction/examples/doc_tree_construction/train/run.py", line 3, in <module>
    from rex.utils.config import ConfigParser
ImportError: cannot import name 'ConfigParser' from 'rex.utils.config' (/home/2023/miniconda3/envs/doctree/lib/python3.10/site-packages/rex/utils/config.py)
+ -b /home/2023/myced/CatalogExtraction/examples/doc_tree_construction/train/base_config.yaml
/home/2023/myced/CatalogExtraction/examples/doc_tree_construction/train/run.sh: 行 23: -b: 未找到命令
+ -c /home/2023/myced/CatalogExtraction/examples/doc_tree_construction/train/custom.yaml -a random_seed=122227 device= data_type=
/home/2023/myced/CatalogExtraction/examples/doc_tree_construction/train/run.sh: 行 25: -c: 未找到命令
+ exit
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tianyumyum** [comment]
In the rex/utils/config.py, it seems to only have class ArgConfig and class YamlConfig. There's no ConfigParser.

**Comment by Spico197** [comment]
Thanks for your reporting. Let me check it. I'll response you ASAP.

**Comment by Spico197** [comment]
Hi there. Thanks for your attention on CED and REx. I've checked the git history, and I think you could solve this problem by upgrading REx to a higher version: `pip install -U pytorch-rex==0.0.10`.

Please let me know if there are any other problems. Thanks again for helping us make both projects better.

**Comment by Spico197** [comment]
I've updated the CED repository, too. Since REx has some break changes without backward compatibility, the latest REx may not support CED. I'll try to upgrade CED to support the latest REx coding style.

**Comment by tianyumyum** [comment]
> I've updated the CED repository, too. Since REx has some break changes without backward compatibility, the latest REx may not support CED. I'll try to upgrade CED to support the latest REx coding style.

Thank you!  I have already solved this problem by using $ pip install -e . as you told in the README.md in CED repository.
